config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users

  resources :posts do
    resources :comments
  end
  root 'welcome#index'
  get 'users/profile', as: 'user_root'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comments, dependent: :destroy
	belongs_to :users

  validates :title, presence: true, length: { minimum: 5 }

	def to_param
		"#{id}-#{title.parameterize}"
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
  has_many :comments

  attr_accessor :password
  EMAIL_REGEX = /\A[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}\z/i
  # validates :name, :presence => true, :uniqueness => true, :length => {:in => 3..20}
  validates :email, :presence => true, :uniqueness => true, :format => EMAIL_REGEX
  validates :password, :confirmation => true
  validates_length_of :password, :in => 6..20, :on => :create

  def to_param
    name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.create(comment_params)

		redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy

    redirect_to post_path(@post)
  end

	private

	def comment_params
	  params.require(:comment).permit(:body)
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :find_post, except: [:index, :create, :new]

  def new
    @post = Post.new()
  end

  def index
    @posts = Post.all
  end

  def update
    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  def edit
  end

  def create
    @post = Post.new(post_params)
    @post.save ? redirect_to(@post) : render('new')
  end

  def destroy
    @post.destroy

    redirect_to posts_path
  end

  def show
  end

  private

  def find_post
    @post = Post.find(params[:id][/(\d)+/])
  end

  def post_params
    params.require(:post).permit(:title, :text, :like)
  end
end

app/controllers/profile_controller.rb
class UsersController < ApplicationController
	def show
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			flash[:notice] = "You signed up successfully"
			flash[:color] = "valid"

		else
			flash[:notice] = "Form is invalid"
			flash[:color] = "valid"
    end

		render "new"
  end

	def show
		@user = User.new
  end

	def user_params
		params.require(:user).permit(:name, :email, :password, :salt, :encrypted_password)
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />

  <title>Blogt</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
</head>

<body>

<%= yield %>

</body>
</html>

app/views/posts/edit.html.erb
<%= form_for :post, url: post_path(@post), method: :patch do|f| %>
	<% if @post.errors.any? %>
 	 	<div id="error_explanation">
 	 	  <h2><%= pluralize(@post.errors.count, "error") %> prohibited
     	 this post from being saved:</h2>
			<ul>
	
			<% @post.errors.full_messages.each do |msg| %>
    		  <li><%= msg %></li>
    		<% end %>
   			</ul>
  		</div>
  <% end %>
	<%= f.label :title %><br>
	<%= f.text_field :title %>

	<%= f.label :text %><br>
	<%= f.text_area :text %>

	<%= f.label :like %><br>
	<%= f.text_field :like %>
	<%= f.submit %>
<% end %>
<%= link_to 'BACK', post_path %>

app/views/posts/index.html.erb
<table>
	<tr>
		<th>Title</th>
		<th>Text</th>
		<th>Like</th>
	</tr>

	<% @posts.each do |post| %>
	 <tr>
	 	<td><%= post.title %></td>
	 	<td><%= post.text %></td>
	 	<td><%= post.like %></td>
	 	<td><%= link_to 'Show',post_path(post) %></td>
	 	<td><%= link_to 'Edit',edit_post_path(post) %></td>
	 	<td><%= link_to 'Destroy', post_path(post), method: :delete, data: {confirm: 'Are you sure?'} %></td>
	 </tr>
	 <% end %>
</table>
<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<%= form_for :post, url: posts_path do|f| %>
	<% if @post.errors.any? %>
 	 	<div id="error_explanation">
 	 	  <h2><%= pluralize(@post.errors.count, "error") %> prohibited
     	 this post from being saved:</h2>
			<ul>
	
			<% @post.errors.full_messages.each do |msg| %>
    		  <li><%= msg %></li>
    		<% end %>
   			</ul>
  		</div>
  <% end %>
	<%= f.label :title %><br>
	<%= f.text_field :title %>

	<%= f.label :text %><br>
	<%= f.text_area :text %>

	<%= f.label :like %><br>
	<%= f.text_field :like %>
	<%= f.submit %>
<% end %>
<%= link_to 'BACK', posts_path %>

app/views/posts/show.html.erb
TItle:
<%= @post.title %>
Text:
<%= @post.text %>
Like:
<%= @post.like %>
<% @post.comments.each do |comment| %>
	Text:
	<%= comment.body %>
  <%= link_to 'Destroy Comment', post_comment_path(@post, comment), method: :delete, data: { confirm: 'Are you sure?'}  %>

<% end %>
Add a comment:
<%= form_for([@post, @post.comments.build]) do |f| %>
	<%= f.label :body %><br>
	<%= f.text_area :body %>

	<%= f.submit %>
<% end %>
<%= link_to 'Back', posts_path %>
| <%= link_to 'Edit', edit_post_path(@post) %>

app/views/users/new.html.erb
 <% @page_title = "UserAuth | Signup" %>
 <div class="Sign_Form">
 	<h1>Sign Up</h1>
 	<%= form_for(:user, :url =>{:controller => 'users', :action =>'create'}) do |f| %>
 		<p>Username:</br> <%= f.text_field :name %> </p>
 		<p>Email	:</br> <%= f.text_field :email %> </p>
 		<p>Password	:</br> <%= f.password_field :password %> </p>
 		<p>Password Confirmation:</br> <%= f.password_field :password_confirmation %> </p>
 		<%= f.submit :Signup %>
 	<% end %>
 	<% if @user.errors.any? %>
 		<ul class="Signup_Errors">
 		<% for message_error in @user.errors.full_messages %>
 			<li>* <%= message_error %></li>
 		<% end %>
 		</ul>
 	<% end %>
 </div>
<p id="notice"><%= notice %></p>

app/views/users/profile.html.erb
<% if user_signed_in? %>
    <span>Здравствуйте, <%= current_user.email %></span>
    <%= link_to 'Выйти', destroy_user_session_path, :method => :delete %>
<% else %>
    <%= link_to 'Войти', new_user_session_path %> или <%= link_to 'Зарегистрироваться', new_user_registration_path %>
<% end %>

app/views/users/show.html.erb
<% if user_signed_in? %>
    <span>Здравствуйте, <%= current_user.email %></span>
    <%= link_to 'Выйти', destroy_user_session_path, :method => :delete %>
<% else %>
    <%= link_to 'Войти', new_user_session_path %> или <%= link_to 'Зарегистрироваться', new_user_registration_path %>
<% end %>

app/views/welcome/index.html.erb
<nav class="top-bar" data-topbar> <ul class="title-area"> <li class="name"> <h1><a href="#">My Site</a></h1> </li> <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone --> <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li> </ul> <section class="top-bar-section"> <!-- Right Nav Section --> <ul class="right"> <li class="active"><a href="#">Right Button Active</a></li> <li class="has-dropdown"> <a href="#">Right Button Dropdown</a> <ul class="dropdown"> <li><a href="#">First link in dropdown</a></li> </ul> </li> </ul> <!-- Left Nav Section --> <ul class="left"> <li><a href="#">Left Nav Button</a></li> </ul> </section> </nav>

<%= link_to 'My Blog', controller: 'posts' %>